/*
 * Copyright (C) 2026 duyongquan <quandy2020@126.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

#ifndef AEROZEN_TOPIC_STATISTICS_HPP_
#define AEROZEN_TOPIC_STATISTICS_HPP_

#include "aerozen/proto/statistic.pb.h"

#include <algorithm>
#include <limits>
#include <memory>
#include <string>

namespace aerozen {
// Forward declarations.
class TopicStatisticsPrivate;

/**
 * @brief Computes the rolling average, min, max, and standard
 * deviation for a set of samples.
 */
class Statistics
{
public:
    /**
     * @brief Default constructor.
     */
    Statistics() = default;

    /**
     * @brief Default destructor.
     */
    ~Statistics() = default;

    /**
     * @brief Update with a new sample.
     * @param[in] _stat New statistic sample.
     */
    void Update(double _stat);

    /**
     * @brief Get the average value.
     * @return the average value.
     */
    double Avg() const;

    /**
     * @brief Get the standard deviation.
     * @return The standard deviation.
     */
    double StdDev() const;

    /**
     * @brief Get the minimum sample value.
     * @return The minimum sample value.
     */
    double Min() const;

    /**
     * @brief Get the maximum sample value.
     * @return The maximum sample value.
     */
    double Max() const;

    /**
     * @brief Get the number of samples.
     * @return The number of samples.
     */
    uint64_t Count() const;

private:
    /**
     * @brief Count of the samples.
     */
    uint64_t count = 0;

    /**
     * @brief Average value.
     */
    double average = 0;

    /**
     * @brief Sum of the squared mean distance between samples. This is
     * used to calculate the standard deviation.
     */
    double sumSquareMeanDist = 0;

    /**
     * @brief Minimum sample.
     */
    double min = std::numeric_limits<double>::max();

    /**
     * @brief Maximum sample.
     */
    double max = std::numeric_limits<double>::min();
};

/**
 * @brief Encapsulates statistics for a single topic. The set of
 * statistics include:
 *
 * 1. Number of dropped messages.
 *    max time between publications.
 * 3. Receive statistics: The reception hz rate, standard
 *    deviation between receiving messages, min time between receiving
 *    messages, and max time between receiving messages.
 *
 * Publication statistics utilize time stamps generated by the
 * publisher. Receive statistics use time stamps generated by the
 * subscriber.
 */
class TopicStatistics
{
public:
    /**
     * @brief Default constructor.
     */
    TopicStatistics();

    /**
     * @brief Copy constructor.
     * @param[in] _stats Statistics to copy.
     */
    TopicStatistics(const TopicStatistics& _stats);

    /**
     * @brief Default destructor.
     */
    ~TopicStatistics();

    /**
     * @brief Update the topic statistics.
     * @param[in] _sender Address of the sender.
     * @param[in] _stamp Publication time stamp.
     * @param[in] _seq Publication sequence number.
     */
    void Update(const std::string& _sender, uint64_t _stamp, uint64_t _seq);

    /**
     * @brief Populate a aerozen::msgs::Metric message with topic
     * statistics.
     * @param[in] _msg Message to populate.
     */
    void FillMessage(aerozen::msgs::Metric& _msg) const;

    /**
     * @brief Get the number of dropped messages.
     * @return Number of dropped messages.
     */
    uint64_t DroppedMsgCount() const;

    /**
     * @brief Get statistics about publication of messages.
     * @return Publication statistics.
     */
    Statistics PublicationStatistics() const;

    /**
     * @brief Get the statistics about reception of messages.
     * @return Reception statistics.
     */
    Statistics ReceptionStatistics() const;

    /**
     * @brief Get the message age statistics.
     * @return Age statistics.
     */
    Statistics AgeStatistics() const;

private:
    /**
     * @brief Private data pointer.
     */
    std::unique_ptr<TopicStatisticsPrivate> dataPtr;
};
}  // namespace aerozen
#endif  // AEROZEN_TOPIC_STATISTICS_HPP_
