/*
 * Compatibility config for aerozen utils.
 */

#ifndef AEROZEN_UTILS_CONFIG_HPP_
#define AEROZEN_UTILS_CONFIG_HPP_

#include "aerozen/config.hpp"

#define AEROZEN_UTILS_MAJOR_VERSION AEROZEN_MAJOR_VERSION
#define AEROZEN_UTILS_MINOR_VERSION AEROZEN_MINOR_VERSION
#define AEROZEN_UTILS_PATCH_VERSION AEROZEN_PATCH_VERSION
#define AEROZEN_UTILS_VERSION AEROZEN_VERSION
#define AEROZEN_UTILS_VERSION_FULL AEROZEN_VERSION_FULL
#define AEROZEN_UTILS_VERSION_NAMESPACE AEROZEN_VERSION_NAMESPACE

#endif  // AEROZEN_UTILS_CONFIG_HPP_
